# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=100)),
                ('user_birth', models.DateTimeField(verbose_name='date published')),
                ('user_sex', models.NullBooleanField()),
                ('user_info', models.TextField()),
            ],
        ),
    ]
